[build]
  command = "npm run build"
  functions = "_functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/services"
  to = "/services.json"
  status = 200
