[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[[headers]]
  for = "/services.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/services"
  to = "/services.json"
  status = 200
